# Nome da nossa pipeline
name: Backend CI Pipeline

# Evento que dispara a pipeline
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

# Definição dos 'jobs' (tarefas) que a pipeline vai executar.
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clona o código do seu repositório.
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Verifique a versão que seu projeto usa

      # Passo 3: Instala as dependências do projeto na pasta do backend.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend

      # Passo 4: Executa os testes na pasta do backend.
      - name: Run tests
        run: pytest
        working-directory: ./backend
